apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: geeksocks-nginx-clusterip
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: geeksocks-nginx-clusterip
  endpoints:
  - port: http
