apiVersion: apps/v1
kind: Deployment
metadata:
  name: geeksocks-mail
spec:
  selector:
    matchLabels:
      run: geeksocks-mail
  replicas: 1
  template:
    metadata:
      labels:
        run: geeksocks-mail
    spec:
      containers:
        - image: morskoi/geeksocks-mail:0.0.5
          imagePullPolicy: Always
          name: geeksocks-mail
          env:
            - name: MAIL_SMTP_LOGIN
              valueFrom:
                secretKeyRef:
                  name: geeksocks-mail-smtp-secret
                  key: username
                  optional: false # same as default; "mysecret" must exist
                            # and include a key named "username"
            - name: MAIL_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geeksocks-mail-smtp-secret
                  key: password
                  optional: false # same as default; "mysecret" must exist
                            # and include a key named "password"
#          ports:
#          - containerPort: 5000
#          volumeMounts:
#          - name: passwordfile
#            mountPath: "/app/secrets/"
#            readOnly: true
#      volumes:
#      - name: passwordfile
#        secret:
#          secretName: geeksocks-mail-smtp-secret
#          optional: false # default setting; "mysecret" must exist
