apiVersion: apps/v1
kind: Deployment
metadata:
  name: geeksocks-nginx
spec:
  selector:
    matchLabels:
      run: geeksocks-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: geeksocks-nginx
    spec:
      initContainers:
        - image: busybox
          name: printhostname
          command: ["sh", "-c", "echo $HOSTNAME > /app/hostname.txt"]
          volumeMounts:
          - name: workdir
            mountPath: "/app" # <-- change the mount path not to overwrite your .jar
      containers:
        - image: morskoi/geeksocks:0.0.8
          #TODO liveness readness
          name: geeksocks-nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/img_s3
              name: s3-volume
            - mountPath: /usr/share/nginx/html/app
              name: workdir
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter:0.3.0'
          args:
            - '-nginx.scrape-uri=http://localhost:80/nginx_status'
          ports:
            - name: nginx-ex-port
              containerPort: 9113
              protocol: TCP
          imagePullPolicy: Always
      volumes:
        - name: s3-volume
          persistentVolumeClaim:
            claimName: csi-s3-pvc-static
            readOnly: false
        - name: workdir
          emptyDir: {}
