apiVersion: apps/v1
kind: Deployment
metadata:
  name: geeksocks-mail
spec:
  selector:
    matchLabels:
      run: geeksocks-mail
  replicas: 1
  template:
    metadata:
      labels:
        run: geeksocks-mail
    spec:
      containers:
        - image: morskoi/geeksocks-mail:0.0.8
          imagePullPolicy: Always
          name: geeksocks-mail
          env:
            - name: MAIL_SMTP_LOGIN
              valueFrom:
                secretKeyRef:
                  name: geeksocks-mail-smtp-secret
                  key: username
                  optional: false
            - name: MAIL_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geeksocks-mail-smtp-secret
                  key: password
                  optional: false
            - name: RMQ_LOGIN
              valueFrom:
                secretKeyRef:
                  name: hello-world-default-user
                  key: username
                  optional: false
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-world-default-user
                  key: password
                  optional: false
          volumeMounts:
          - name: certs
            mountPath: "/app/certs/"
            readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: rmq-client-certificate
          optional: false
