apiVersion: apps/v1
kind: Deployment
metadata:
  name: geeksocks-nginx
spec:
  selector:
    matchLabels:
      run: geeksocks-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: geeksocks-nginx
    spec:
      containers:
        - image: morskoi/geeksocks:0.0.2
          name: geeksocks-nginx
          ports:
          - containerPort: 80
        #    containerPort: 443
