apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geeksocks-ingress
spec:
#  ingressClassName: nginx-example
  tls:
  - hosts:
    - k8s.geeksocks.ru
    secretName: geeksocks-tls-secret
  rules:
  - host: k8s.geeksocks.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: geeksocks-nginx-clusterip
            port: 
              number: 80
