apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-site
  namespace: default
spec:
  selector:
    matchLabels:
      run: geeksocks-nginx
  endpoints:
  - port: metrics
    interval: 30s
