apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: definition
    app.kubernetes.io/part-of: rabbitmq
  name: persistence-definition-server-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
