apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: hello-world
spec:
  persistence:
    storageClassName: local-storage
    storage: "200Mi"
  tls:
    secretName: rmq-server-certificate
    caSecretName: rmq-server-certificate
  rabbitmq:
    additionalConfig: |
      ssl_options.fail_if_no_peer_cert = true
      listeners.tcp = none
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:	
            - name: rabbitmq
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: amqps
                timeoutSeconds: 5

